import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import TopArea from "@/components/TopArea";
import Provider from "@/providers";

const comfortaa = Comfortaa({
  variable: "--font-comfortaa-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ChatIn",
  description: "Generated by ChatIn",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${comfortaa.variable} antialiased `}>
        <Provider>
          <div className="dark:bg-theme-dark bg-theme-light relative w-full min-h-screen overflow-hidden">
            <TopArea />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
