import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "../globals.css";
import Provider from "@/providers";
import ThemeToggle from "@/components/ThemeToggle";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const comfortaa = Comfortaa({
  variable: "--font-comfortaa-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ChatIn",
  description: "Generated by ChatIn",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${comfortaa.variable} antialiased dark:bg-theme-dark bg-theme-light relative`}
      >
        <Provider>
          <ThemeToggle />
          {children}
          <ReactQueryDevtools initialIsOpen={false} buttonPosition="top-left" />
        </Provider>
      </body>
    </html>
  );
}
